---
- name: Clone Certbot into configured directory.
  git:
    repo: "{{ certbot_repo }}"
    dest: "{{ certbot_dir }}"
    version: "{{ certbot_version }}"
    update: "{{ certbot_keep_updated }}"
    force: true
  tags: molecule-idempotence-notest

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_dir }}/certbot-auto"

- name: Ensure certbot-auto is executable.
  file:
    path: "{{ certbot_script }}"
    mode: 0755

- name: Install EFF's certbot
  command: "{{ certbot_script }} --install-only -n"
  args:
    creates: /opt/eff.org/certbot

- name: Install plugins
  pip:
    name: "file:///opt/certbot/certbot-dns-{{ item }}"
    virtualenv: /opt/eff.org/certbot/venv
  loop: "{{ certbot_dns_plugins }}"

- name: Configuration directory
  file:
    dest: /etc/letsencrypt
    state: directory

- name: Configuration file
  copy:
    dest: /etc/letsencrypt/cli.ini
    content: |
      # Managed by Ansible

      # Use old chain to keep compatibility with older Android for 6 additional months
      # https://community.letsencrypt.org/t/certbot-users-preparing-for-the-isrg-root-transition-january-11-2021/138059
      preferred-chain = DST Root CA X3
    owner: root
    group: root
    mode: "0400"
