---
- name: Install ssl-cert to generate snakeoil cert
  package:
    name: ssl-cert

- name: Assemble combined snakeoil
  shell: cat "/etc/ssl/private/ssl-cert-snakeoil.key" "/etc/ssl/certs/ssl-cert-snakeoil.pem" > "/etc/ssl/private/ssl-cert-snakeoil-combined.pem"
  args:
    creates: /etc/ssl/private/ssl-cert-snakeoil-combined.pem

- name: Combined snakeoil mode
  file:
    path: /etc/ssl/private/ssl-cert-snakeoil-combined.pem
    mode: 0400

- name: Ensure certbot-auto is executable.
  file:
    path: "/etc/letsencrypt/renewal-hooks/{{ item }}"
    mode: 0644
    state: directory
  with_items:
    - pre
    - post
    - deploy

- name: Ensure certbot-auto is executable.
  file:
    path: "/etc/ssl/{{ item }}"
    mode: 0700
    state: directory
  with_items: "{{ certbot_hooks }}"

- name: Ensure renew deploy hooks are in place.
  template:
    src: "{{ item }}-renew-deploy.j2"
    dest: "/etc/letsencrypt/renewal-hooks/deploy/{{ item }}"
    owner: root
    group: root
    mode: 0555
  with_items: "{{ certbot_hooks }}"

- name: Ensure renew post hooks are in place.
  template:
    src: "{{ item }}-renew-post.j2"
    dest: "/etc/letsencrypt/renewal-hooks/post/{{ item }}"
    owner: root
    group: root
    mode: 0555
  with_items: "{{ certbot_hooks }}"
