---
- name: Converge
  hosts: all

  vars:
    certbot_auto_renew_user: root

  pre_tasks:
    - name: Update cache
      apt:
        update_cache: yes

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
