---
- name: Converge
  hosts: all
  roles:
    - role: dev-sec.os-hardening
      tags: molecule-idempotence-notest

    - dev-sec.ssh-hardening

    - ansible-role-certbot

  vars:
    certbot_auto_renew_user: root
