---
- name: Converge
  hosts: all

  vars:
    certbot_auto_renew_user: root
    certbot_dns_plugins:
      - route53

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
