---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # Debian
  # - name: molecule-common-debian9-systemd
  #   image: jrei/systemd-debian:9
  #   privileged: True
  #   volumes:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #   command: /lib/systemd/systemd
  - name: molecule-common-debian10-systemd
    image: jrei/systemd-debian:10
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
  # Ubuntu
  - name: molecule-common-ubuntu1804
    image: jrei/systemd-ubuntu:18.04
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
