---
dependency:
  name: galaxy
  options:
    force: False
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: molecule-common-debian10-systemd
    image: jrei/systemd-debian:10
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
  # # Ubuntu
  # - name: molecule-common-ubuntu1804
  #   image: jrei/systemd-ubuntu:18.04
  #   privileged: True
  #   volumes:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
