---
dependency:
  name: galaxy
  options:
    force: False
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: molecule-certbot-debian11
    image: jrei/systemd-debian:11
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
