---
- hosts: all
  tasks:
    - name: Install requirements
      become: yes
      pip:
        executable: pip3
        name: "{{ item }}"
        state: present
      with_items:
        - molecule
        - molecule[docker]
